@echo off
set JAVA_HOME=C:\Program Files\Java\jdk-17
echo Compiling project...
javac -d . Main.java
echo Compiling tests...
javac -cp .;lib\junit.jar -d . MainTest.java
echo Running tests...
java -cp .;lib\junit.jar;lib\hamcrest-core.jar org.junit.runner.JUnitCore Task_1.MainTest
echo Running program...
java Task_1.Main 2 2 2
pause